### ISSUE TITLE
Create contributing guide for non-technical users

### ISSUE THREAD

**Issue by ropolomx** [BeeBiome-consortium/beebiome-data-portal#11]
Create a document for non-technical members to make updates to About pages, "Wiki", etc.

**Comment by ropolomx** [comment]
Addressed by #14 submitted by @Juke34

**Comment by Juke34** [comment]
I would say partially addressed because I do not mention anything about Wiki. ^^

**Comment by ropolomx** [comment]
Good point. I think since the Wiki pages of the portal (which are more like catalogue) are Markdown documents, the contributing guidelines would also apply. Thanks for suggesting those guidelines! Those will be a great addition.

**Comment by Juke34** [comment]
I understand now, yes the wiki is not really a wiki. Well we shoud at least add a `Edit on GitHub` sticker on top left that point to the [wiki folder](https://github.com/BeeBiome-consortium/beebiome-data-portal/tree/master/beebiome-docs/wiki).
If I understand how it works we cannot see the rendering of a modification without making a proper deployment right? If it is the case I would suggest to move the doc to something like `readthedocs`.

**Comment by ropolomx** [comment]
I think those are excellent ideas! Thank you, @Juke34 .`readthedocs` is a very good suggestion, and it might work very well with the documentation of the codebase that @greysaruman is doing
